repos:
    - repo: 'https://github.com/pre-commit/mirrors-isort'
      rev: v5.10.1
      hooks:
        - id: isort
    - repo: 'https://github.com/codespell-project/codespell'
      rev: v2.1.0
      hooks:
        - id: codespell
          args:
            - '--skip="./.*,*.csv,*.json,*.pyc,./docs/_build/*,./htmlcov/*"'
            - '--quiet-level=2'
          exclude_types:
            - csv
            - json
    - repo: 'https://github.com/psf/black'
      rev: 22.3.0
      hooks:
        - id: black
          args:
            - '--safe'
            - '--quiet'
    - repo: 'https://github.com/pycqa/flake8'
      rev: 4.0.1
      hooks:
        - id: flake8
          additional_dependencies:
            - flake8-docstrings==1.6.0
            - pydocstyle==6.1.1
          files: ^main.py|(boilerplate|tests)\/.+\.py$
    - repo: 'https://github.com/PyCQA/bandit'
      rev: 1.7.4
      hooks:
        - id: bandit
          args:
            - '--quiet'
            - '--configfile=pyproject.toml'
          additional_dependencies: [ toml ]

    - repo: 'https://github.com/myint/rstcheck'
      rev: 3f929574
      hooks:
        - id: rstcheck
          args:
          - '--config=pyproject.toml'
          additional_dependencies: [ toml ]
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1
      hooks:
        - id: pydocstyle
          additional_dependencies: [ toml ]
    - repo: 'https://github.com/pre-commit/pre-commit-hooks'
      rev: v4.1.0
      hooks:
        - id: check-yaml
          args: [--unsafe]
        - id: end-of-file-fixer
        - id: trailing-whitespace
